### ISSUE TITLE
video

### ISSUE THREAD

**Issue by heervisscher** [abmaonline/aemfed#1]
any way you can make a video of this?
I'd love to promote it.

**Comment by abmaonline** [comment]
Cool!

A short video/gif/animation for the readme is on the todo list, since it is best way to show the effect. Still looking for a good sample project, but it will probably be the wknd project again, with some modifications to the Less structure to improve the performance of rendering the clientlibs (now it's around 3s for the styling, which diminishes the effect a bit).

Any recommendations or requests for a video based on the expected audience?

**Comment by heervisscher** [comment]
expected audience I would say are AEM-dev / frontenders

**Comment by abmaonline** [comment]
Did some restructuring on the wknd project clientlibs and now updating the styling for components by aem takes around 100-200ms 💪 

Will try to make a video of it in the next few days.

https://github.com/abmaonline/aem-guides-wknd/tree/move-clientlibs-to-components

**Comment by heervisscher** [comment]
thank you!

**Comment by abmaonline** [comment]
Got a small intro showing some of the key features: https://www.youtube.com/watch?v=sHIHSISOL0w

Also attached as an animated gif for use in the readme (at the moment a gif is one of the few ways to get in animation in your github readme).

![demo-800](https://user-images.githubusercontent.com/4146168/42420783-74cf2b58-82cb-11e8-8b36-15bcea9c621e.gif)
