### ISSUE TITLE
Github dependencies causing issues on NPM install

### ISSUE THREAD

**Issue by jpgcodecr** [abmaonline/aemfed#21]
Aemsync and less-tree dependencies are pulled in the package.json from github.

"aemsync": "https://github.com/abmaonline/aemsync/tarball/a2bed54",
 "less-tree": "https://github.com/abmaonline/less-tree/tarball/58baecb",

This causes authentication issues when trying to install aemfed package. 
```
npm ERR! code E401
npm ERR! Unable to authenticate, need: Basic realm="GitHub"
```

Please could you update the dependencies to be pulled from NPM instead?

**Comment by abmaonline** [comment]
Just tried it locally and did not receive this error. Do you maybe use any private repositories that have different authentication methods defined in the env?

These two dependencies are not in npm, because they were a temporary solution for missing functionality that ideally should be part of the original modules. I will try to get them in the original module or publish them as npm packages either way (timeline will depend on those integrations).

**Comment by jpgcodecr** [comment]
After digging into it it was a .npmrc with wrong config in my side. Thanks for taking a look. 
Closing this ticket.
